export const cities = [
    { name: 'Galali', country_id: 1 },
    { name: 'Al Hidd', country_id: 1 },
    { name: 'Arad', country_id: 1 },
    { name: 'Samaheej', country_id: 1 },
    { name: 'Busaiteen', country_id: 1 },
    { name: 'Al Sayh', country_id: 1 },
    { name: 'Al Dair', country_id: 1 },
    { name: 'Amwaj', country_id: 1 },
    { name: 'Diyar Muharraq', country_id: 1 },
    { name: 'Dilmunia island', country_id: 1 },
    { name: 'Diplomatic Area', country_id: 1 },
    { name: 'Qudaibiya', country_id: 1 },
    { name: 'Adliya', country_id: 1 },
    { name: 'Mahooz', country_id: 1 },
    { name: 'umm al hassam', country_id: 1 },
    { name: 'Juffair', country_id: 1 },
    { name: 'Al Ghurayfah', country_id: 1 },
    { name: 'Salmaniya', country_id: 1 },
    { name: 'Al Niam', country_id: 1 },
    { name: 'Bu Ghazal', country_id: 1 },
    { name: 'Segaya', country_id: 1 },
    { name: 'Bilad Al Qadeem', country_id: 1 },
    { name: 'Salhiya', country_id: 1 },
    { name: 'Zinj', country_id: 1 },
    { name: 'Sanabis', country_id: 1 },
    { name: 'Jidhafs', country_id: 1 },
    { name: 'Bu Quwah', country_id: 1 },
    { name: 'Reef Island', country_id: 1 },
    { name: 'Bahrain Bay', country_id: 1 },
    { name: 'Burhama', country_id: 1 },
    { name: 'Daih', country_id: 1 },
    { name: 'Karbabad', country_id: 1 },
    { name: 'Seef', country_id: 1 },
    { name: 'al Maqsha', country_id: 1 },
    { name: 'Abu Saiba', country_id: 1 },
    { name: 'Saar', country_id: 1 },
    { name: 'Jeblat Hebshi', country_id: 1 },
    { name: 'Barbar', country_id: 1 },
    { name: 'Diraz', country_id: 1 },
    { name: 'Bani jamra', country_id: 1 },
    { name: 'Northern city', country_id: 1 },
    { name: 'Nurana islands', country_id: 1 },
    { name: 'Budaiya', country_id: 1 },
    { name: 'Karranah', country_id: 1 },
    { name: 'Janbiyah', country_id: 1 },
    { name: 'Al Jasra', country_id: 1 },
    { name: 'Hamala', country_id: 1 },
    { name: 'Buri', country_id: 1 },
    { name: 'Damistan', country_id: 1 },
    { name: 'Karzakkan', country_id: 1 },
    { name: 'Malkiya', country_id: 1 },
    { name: 'Hamad Town', country_id: 1 },
    { name: 'Sadad', country_id: 1 },
    { name: 'Dar kulaib', country_id: 1 },
    { name: 'Zallaq', country_id: 1 },
    { name: 'Aali', country_id: 1 },
    { name: 'Isa Town', country_id: 1 },
    { name: 'Zayed Town', country_id: 1 },
    { name: 'Tubli', country_id: 1 },
    { name: 'Nabih Saleh', country_id: 1 },
    { name: 'Sanad', country_id: 1 },
    { name: 'Sitra', country_id: 1 },
    { name: 'Nuwaidrat', country_id: 1 },
    { name: 'Al Eker', country_id: 1 },
    { name: "Ma'meer", country_id: 1 },
    { name: 'Awali', country_id: 1 },
    { name: 'Riffa', country_id: 1 },
    { name: 'Askar', country_id: 1 },
    { name: 'Jaw', country_id: 1 },
    { name: 'Durrat AlBahrain', country_id: 1 },
    { name: 'Hawar Island', country_id: 1 },
    { name: 'Jidali', country_id: 1 },
    { name: 'Um Al Naasan', country_id: 1 },
    { name: 'Sehla', country_id: 1 },
    { name: 'Ras Ruman', country_id: 1 },
    { name: 'Jannusan', country_id: 1 },
    { name: 'Al Khammis', country_id: 1 },
    { name: 'Al Guful', country_id: 1 },
    { name: 'Al Gadam', country_id: 1 },
    { name: 'Al Muhammadiya', country_id: 1 },
    { name: 'Hoora', country_id: 1 },
    { name: 'Jidda island', country_id: 1 },
    { name: 'Tashan', country_id: 1 },
    { name: 'Sakhir', country_id: 1 },
    { name: 'Maqabah', country_id: 1 },
    { name: 'Jurdab', country_id: 1 },
    { name: 'Kawarah', country_id: 1 },
    { name: 'Al Dar Island', country_id: 1 },
    { name: 'Salmabad', country_id: 1 },
    { name: 'Al Musala', country_id: 1 },
    { name: 'Al Qurayyah', country_id: 1 },
    { name: 'Shahrakan', country_id: 1 },
    { name: 'Ras Albar', country_id: 1 },
    { name: 'Al Markh', country_id: 1 },
    { name: 'Jid Alhaj', country_id: 1 },
    { name: 'Manama', country_id: 1 },
    { name: 'Muharraq', country_id: 1 },
    { name: 'Shakhura', country_id: 1 },
    { name: 'AlFateh', country_id: 1 },
    { name: 'AlQalah', country_id: 1 }
]